version: "3"
services:
  php:
    build: ./build/php
    image: php-7.2.34
    container_name: php
    restart: always
    volumes:
      - ./build/php/php.ini:/usr/local/etc/php/php.ini
      - ./build/php/composer:/usr/local/bin/composer
      - .:/app
    ports:
      - "8818:8818"
  nginx:
    image: "nginx"
    container_name: nginx
    restart: always
    ports:
      - "8819:80"
    volumes:
      - ./build/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./build/nginx/server.d:/etc/nginx/server.d
      - .:/app
  mysql:
    image: "mysql"
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1236
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
