version: "3"
services:
  php:
    image: tbphp/php-7.2.34-fpm
    container_name: php
    restart: always
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      - mysql
      - redis
  chat:
    image: tbphp/php-7.2.34-fpm
    container_name: chat
    restart: always
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      - mysql
      - redis
    entrypoint: php /app/artisan ratchet:serve --driver=WsServer -z
    ports:
      - "8818:8818"
  nginx:
    image: "nginx"
    container_name: nginx
    restart: always
    ports:
      - "8819:80"
    working_dir: /app
    depends_on:
      - php
    volumes:
      - ./build/nginx/nginx.conf:/etc/nginx/nginx.conf
      - .:/app
  mysql:
    image: "mysql"
    container_name: mysql
    restart: always
    privileged: true
    environment:
      MYSQL_ROOT_PASSWORD: 1236
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
    ports:
      - "33601:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  redis:
    image: "redis"
    container_name: redis
    restart: always
    volumes:
      - redis-data:/data
volumes:
  mysql-data:
  redis-data:
